//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Totem.Services.AlumnoSv {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AlumnoSv.IAlumnoWs")]
    public interface IAlumnoWs {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumnoWs/obtenerReporteAlumno", ReplyAction="http://tempuri.org/IAlumnoWs/obtenerReporteAlumnoResponse")]
        string obtenerReporteAlumno(string run);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumnoWs/obtenerReporteAlumno", ReplyAction="http://tempuri.org/IAlumnoWs/obtenerReporteAlumnoResponse")]
        System.Threading.Tasks.Task<string> obtenerReporteAlumnoAsync(string run);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumnoWs/validaLoginAlumno", ReplyAction="http://tempuri.org/IAlumnoWs/validaLoginAlumnoResponse")]
        string validaLoginAlumno(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumnoWs/validaLoginAlumno", ReplyAction="http://tempuri.org/IAlumnoWs/validaLoginAlumnoResponse")]
        System.Threading.Tasks.Task<string> validaLoginAlumnoAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumnoWs/cambiarClaveUsuario", ReplyAction="http://tempuri.org/IAlumnoWs/cambiarClaveUsuarioResponse")]
        string cambiarClaveUsuario(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumnoWs/cambiarClaveUsuario", ReplyAction="http://tempuri.org/IAlumnoWs/cambiarClaveUsuarioResponse")]
        System.Threading.Tasks.Task<string> cambiarClaveUsuarioAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumnoWs/obtenerReporteAlumnoWs", ReplyAction="http://tempuri.org/IAlumnoWs/obtenerReporteAlumnoWsResponse")]
        Totem.VO.RespuestaReporte obtenerReporteAlumnoWs(string run);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumnoWs/obtenerReporteAlumnoWs", ReplyAction="http://tempuri.org/IAlumnoWs/obtenerReporteAlumnoWsResponse")]
        System.Threading.Tasks.Task<Totem.VO.RespuestaReporte> obtenerReporteAlumnoWsAsync(string run);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAlumnoWsChannel : Totem.Services.AlumnoSv.IAlumnoWs, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AlumnoWsClient : System.ServiceModel.ClientBase<Totem.Services.AlumnoSv.IAlumnoWs>, Totem.Services.AlumnoSv.IAlumnoWs {
        
        public AlumnoWsClient() {
        }
        
        public AlumnoWsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AlumnoWsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlumnoWsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlumnoWsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string obtenerReporteAlumno(string run) {
            return base.Channel.obtenerReporteAlumno(run);
        }
        
        public System.Threading.Tasks.Task<string> obtenerReporteAlumnoAsync(string run) {
            return base.Channel.obtenerReporteAlumnoAsync(run);
        }
        
        public string validaLoginAlumno(string username, string password) {
            return base.Channel.validaLoginAlumno(username, password);
        }
        
        public System.Threading.Tasks.Task<string> validaLoginAlumnoAsync(string username, string password) {
            return base.Channel.validaLoginAlumnoAsync(username, password);
        }
        
        public string cambiarClaveUsuario(string username, string password) {
            return base.Channel.cambiarClaveUsuario(username, password);
        }
        
        public System.Threading.Tasks.Task<string> cambiarClaveUsuarioAsync(string username, string password) {
            return base.Channel.cambiarClaveUsuarioAsync(username, password);
        }
        
        public Totem.VO.RespuestaReporte obtenerReporteAlumnoWs(string run) {
            return base.Channel.obtenerReporteAlumnoWs(run);
        }
        
        public System.Threading.Tasks.Task<Totem.VO.RespuestaReporte> obtenerReporteAlumnoWsAsync(string run) {
            return base.Channel.obtenerReporteAlumnoWsAsync(run);
        }
    }
}
